version: '3.8'
volumes:
  static:
services:
  api:
    container_name: api
    build:
      context: ./currencies_backend
    ports:
      - '3000:3000'
networks:
  default:
    external:
      name: timeweeb
