version: '3.8'
volumes:
  static:
services:
  proxy:
    image: nginx:1.20
    container_name: proxy
    depends_on:
      - api
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./currencies_proxy/nginx.conf:/etc/nginx/nginx.conf
  ui:
    container_name: ui
    build:
      context: ./currencies_frontend
    volumes:
      - static:/app/dist/
  api:
    container_name: api
    build:
      context: ./currencies_backend
    ports:
      - '3000:3000'
    depends_on:
      - ui
    volumes:
      - static:/app/front/
